# Generated by Django 4.2.4 on 2023-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_alter_category_options_alter_men_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
