# Generated by Django 4.2.4 on 2023-08-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0004_category_slug_men_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='men',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='men.message'),
        ),
    ]
