# Generated by Django 4.2.4 on 2023-08-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_message_men_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='men.men'),
        ),
    ]
