# Generated by Django 4.2.4 on 2023-08-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0006_remove_men_message_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='men',
        ),
    ]
