# Generated by Django 4.2.4 on 2023-08-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0007_rename_message_message_men'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'verbose_name': 'Известные мужчинки', 'verbose_name_plural': 'Известные мужчинки'},
        ),
    ]
